# Generated by Django 3.1 on 2020-10-27 08:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='discount',
            fields=[
                ('discount_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('discount_amount', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 10, 27, 8, 45, 57, 389315, tzinfo=utc))),
                ('valid_date', models.DateTimeField()),
                ('discount_type', models.IntegerField(choices=[(1, 'big mart sell'), (2, 'festive offer'), (3, 'vegetable mania'), (4, 'pulses play'), (5, 'the farmer day')])),
            ],
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'user address'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user list'},
        ),
        migrations.CreateModel(
            name='user_payment',
            fields=[
                ('payment_detail_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('card_number', models.CharField(max_length=200)),
                ('cvv_number', models.IntegerField()),
                ('valid_from', models.DateTimeField()),
                ('valid_upto', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
            options={
                'verbose_name': 'user payment details',
            },
        ),
    ]
