# Generated by Django 3.1 on 2020-10-27 13:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201027_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Product Discounts'},
        ),
        migrations.AlterField(
            model_name='discount',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 13, 11, 6, 719580, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 10, 27, 13, 11, 6, 719580, tzinfo=utc))),
                ('modified_date', models.DateTimeField(default=datetime.datetime(2020, 10, 27, 13, 11, 6, 719580, tzinfo=utc))),
                ('status', models.IntegerField(choices=[(1, 'Paid'), (2, 'Unpaid'), (3, 'Delivered'), (4, 'Returned')])),
                ('amount', models.FloatField()),
                ('delivery_mdethod', models.IntegerField(choices=[(1, 'Cash On delivery'), (2, 'Online Paid')], verbose_name='payment_method')),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.address')),
                ('discount_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.discount')),
                ('payment_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_payment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
            options={
                'verbose_name': 'User Orders',
            },
        ),
    ]
