# Generated by Django 3.1 on 2020-10-27 13:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201027_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'user addres'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Product Discount'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'User Order'},
        ),
        migrations.AlterModelOptions(
            name='user_payment',
            options={'verbose_name': 'user payment detail'},
        ),
        migrations.AlterField(
            model_name='discount',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 13, 16, 17, 881260, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 13, 16, 17, 881260, tzinfo=utc)),
        ),
    ]
