# Generated by Django 3.1 on 2020-10-28 04:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20201028_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 4, 37, 14, 260524, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 4, 37, 14, 260524, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='seller_product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 4, 37, 14, 272536, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='seller_product',
            name='selling_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 4, 37, 14, 272536, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_cart',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 4, 37, 14, 276524, tzinfo=utc)),
        ),
    ]
