# Generated by Django 3.1 on 2020-11-09 01:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0009_auto_20201028_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 1, 53, 44, 304969, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 1, 53, 44, 304969, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='seller_product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 1, 53, 44, 327561, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='seller_product',
            name='selling_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 1, 53, 44, 327561, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_cart',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 1, 53, 44, 329556, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=200, unique=True)),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user list',
            },
        ),
        migrations.AlterField(
            model_name='address',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profile'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profile'),
        ),
        migrations.AlterField(
            model_name='user_payment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profile'),
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
